name: Api ::Coverage Report

on:
  pull_request:
    paths:
      - "modules/services/api/**" 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests with Coverage
        run: npm run test:cov
        working-directory: modules/services/api/

      - name: Comment PR with Jest Coverage
        uses: MishaKav/jest-coverage-commenter-action@v1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
