#!/bin/bash

# ---------------------------------------------------------------------------- #
#                                     Doc                                      #
# ---------------------------------------------------------------------------- #

echo "
# ---------------------------------------------- #
#                Apply Migrations                #
# ---------------------------------------------- #
"

# ---------------------------------------------------------------------------- #
#                                     Task                                     #
# ---------------------------------------------------------------------------- #

echo "Starting Postgres..."
sudo service postgresql start >> /dev/null

echo "Compiling migrations..."
npm run --workspace @vidya/database build

echo "Applying migrations..."
npx --workspace @vidya/database typeorm migration:run -d ./dist/services/database/main.js
