name: Api // Tests

on:
  push:
    paths:
      - "modules/services/api/**"

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests with Coverage
        run: npm run test:cov | tee ./coverage/coverage.txt
        working-directory: modules/services/api/

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-path: ./modules/services/api/coverage/coverage.txt
          coverage-summary-path: ./modules/services/api/coverage/coverage-summary.json
          junitxml-path: ./modules/services/api/coverage/junit.xml
