name: Api // Tests

on:
  push:
    paths:
      - "modules/services/api/**"

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests with Coverage
        run: npm run test:cov
        working-directory: modules/services/api/

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        working-directory: modules/services/api/
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
